import Link from "next/link";
import { submitFeedback } from "./actions";

const copy = {
  de: { kicker: "Haltestellen-Check", title: "Wie gut ist deine Haltestelle?", intro: "Bewerte die Haltestelle aus deiner persönlichen Sicht. Deine Antworten helfen, konkrete Verbesserungen zu planen.", overall: "Wie bewertest du die Haltestelle insgesamt?", details: "Deine Bewertung im Detail", clean: "Sauberkeit", safe: "Sicherheitsgefühl", access: "Barrierefreiheit", info: "Fahrgastinformation", shelter: "Wetterschutz", equipment: "Was ist an der Haltestelle vorhanden?", comment: "Was soll konkret verbessert werden?", email: "E-Mail (optional)", consent: "Ich darf zu meiner Rückmeldung kontaktiert werden.", send: "Feedback absenden", yes: "Ja", no: "Nein", features: ["Wetterschutz", "Sitzgelegenheit", "Beleuchtung"] },
  it: { kicker: "Check della fermata", title: "Com'è la tua fermata?", intro: "Valuta la fermata dal tuo punto di vista. Le tue risposte aiutano a pianificare miglioramenti concreti.", overall: "Come valuti complessivamente la fermata?", details: "La tua valutazione nel dettaglio", clean: "Pulizia", safe: "Senso di sicurezza", access: "Accessibilità", info: "Informazioni ai passeggeri", shelter: "Protezione dalle intemperie", equipment: "Cosa è presente alla fermata?", comment: "Cosa dovrebbe essere migliorato concretamente?", email: "E-mail (facoltativa)", consent: "Posso essere contattato/a in merito al mio feedback.", send: "Invia feedback", yes: "Sì", no: "No", features: ["Pensilina", "Posti a sedere", "Illuminazione"] },
  en: { kicker: "Stop check", title: "How good is your stop?", intro: "Rate the stop from your personal perspective. Your answers help plan specific improvements.", overall: "How would you rate the stop overall?", details: "Your rating in detail", clean: "Cleanliness", safe: "Feeling of safety", access: "Accessibility", info: "Passenger information", shelter: "Weather protection", equipment: "What is available at the stop?", comment: "What specifically should be improved?", email: "Email (optional)", consent: "I may be contacted about my feedback.", send: "Submit feedback", yes: "Yes", no: "No", features: ["Shelter", "Seating", "Lighting"] },
};

function Rating({ name, label }: { name: string; label: string }) {
  return <fieldset className="rating-field"><legend>{label}</legend><div>{[1,2,3,4,5].map((value) => <label key={value}><input type="radio" name={name} value={value} required /><span>{value}</span></label>)}</div><small>1</small><small>5</small></fieldset>;
}

export default async function FeedbackPage({ searchParams }: { searchParams: Promise<{ stop?: string; lang?: string; name?: string }> }) {
  const params = await searchParams;
  const language = (["de", "it", "en"].includes(params.lang ?? "") ? params.lang : "de") as keyof typeof copy;
  const text = copy[language];
  const featureNames = ["has_shelter", "has_seating", "has_lighting"];
  return <main className="feedback-page"><Link href="/">← südtirolmobil feedback</Link><section><span>{text.kicker}</span><h1>{text.title}</h1><h2>{params.name ?? "Bus stop"}</h2><p>{text.intro}</p><form action={submitFeedback}><input type="hidden" name="stop_id" value={params.stop ?? ""} /><input type="hidden" name="language" value={language} /><Rating name="overall_rating" label={text.overall} /><h3>{text.details}</h3><div className="detail-ratings"><Rating name="cleanliness_rating" label={text.clean} /><Rating name="safety_rating" label={text.safe} /><Rating name="accessibility_rating" label={text.access} /><Rating name="information_rating" label={text.info} /><Rating name="shelter_rating" label={text.shelter} /></div><fieldset className="features"><legend>{text.equipment}</legend>{text.features.map((feature, index) => <div key={feature}><strong>{feature}</strong><label><input type="radio" name={featureNames[index]} value="yes" required /> {text.yes}</label><label><input type="radio" name={featureNames[index]} value="no" required /> {text.no}</label></div>)}</fieldset><label>{text.comment}<textarea name="comment" maxLength={2000} rows={5} /></label><label>{text.email}<input type="email" name="email" maxLength={320} /></label><label className="consent"><input type="checkbox" name="consent_to_contact" /> {text.consent}</label><button disabled={!params.stop} type="submit">{text.send}</button></form></section></main>;
}
